version: 2.1
 
jobs:
  test:
    docker:
      - image: ghcr.io/foundry-rs/foundry:latest
    steps:
      - checkout
      - run:
          name: Install submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
            - v1-forge-{{ checksum "forge.toml" }}
            - v1-forge-
      - run:
          name: Build
          command: forge build
      - save_cache:
          key: v1-forge-{{ checksum "forge.toml" }}
          paths:
            - ~/.foundry
            - out
      - run:
          name: Test
          command: forge test -vvv
 
workflows:
  main:
    jobs:
      - test
